apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        imagePullPolicy: Always
        image: wordpress:4.8-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: wp-secret
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: wp-secret
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: database
              name: wp-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: wordpress
        VolumMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      - volumes:
      - name: wordpress-persistent-storage
        hostPath:
          path: /data/wordpress